/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    AssistantMessage: typeof import('./components/chat/AssistantMessage.vue')['default']
    AuthLayout: typeof import('./components/layout/AuthLayout.vue')['default']
    BrandLogo: typeof import('./components/common/BrandLogo.vue')['default']
    ChatComposer: typeof import('./components/chat/ChatComposer.vue')['default']
    ChatWelcome: typeof import('./components/chat/ChatWelcome.vue')['default']
    CitationItem: typeof import('./components/citation/CitationItem.vue')['default']
    CitationList: typeof import('./components/citation/CitationList.vue')['default']
    ConversationDialog: typeof import('./components/chat/ConversationDialog.vue')['default']
    ConversationSidebar: typeof import('./components/chat/ConversationSidebar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    MarkdownContent: typeof import('./components/common/MarkdownContent.vue')['default']
    MessageList: typeof import('./components/chat/MessageList.vue')['default']
    ProfileDialog: typeof import('./components/profile/ProfileDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserMessage: typeof import('./components/chat/UserMessage.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
